
<style scoped lang="less">
@import "../../assets/style.less";
</style>
<template>
  <div class="demo-box">
    <k-navbar
        l-icon="icon-CUI-icon-chevron-lef"
        title="图标"
        :theme="['#5c6b77', '#fff']"
        :l-click="licon"
        type="text"
    >
    </k-navbar>
    <div class="icon-list" v-for="(list,index) in icon" :key="index">
       <i :class="'iconfont '+list.icon"></i>
       <span>{{list.icon}}</span>
    </div>
  </div>
</template>
<script>
export default {
  components:{
    
  },
  name: 'icon',
  data () {
    return {
        icon:[
            {
                icon:"icon-right",
            },{
                icon:"icon-buju",
            },{
                icon:"icon-share",
            },{
                icon:"icon-biaoqian1",
            },{
                icon:"icon-Git-",
            },{
                icon:"icon-dankuang-tixing",
            },{
                icon:"icon-share1",
            },{
                icon:"icon-liulan1",
            },{
                icon:"icon-biaodan",
            },{
                icon:"icon-xuanzhong",
            },{
                icon:"icon-fenxiang",
            },{
                icon:"icon-xiala",
            },{
                icon:"icon-kaiguanguan",
            },{
                icon:"icon-sousuo1",
            },{
                icon:"icon-shijian",
            },{
                icon:"icon-cai",
            },{
                icon:"icon-buzhou",
            },{
                icon:"icon-tiaoshi",
            },{
                icon:"icon-fenxiangfangshi",
            },{
                icon:"icon-guanfangbanben",
            },{
                icon:"icon-gongnengdingyi",
            },{
                icon:"icon-jishufuwu",
            },{
                icon:"icon-ceshishenqing",
            },{
                icon:"icon-jinggao",
            },{
                icon:"icon-peiwangyindao",
            },{
                icon:"icon-shebeikaifa",
            },{
                icon:"icon-quanxianshenpi",
            },{
                icon:"icon-shujukanban",
            },{
                icon:"icon-yingyongguanli",
            },{
                icon:"icon-zhanghaoquanxianguanli",
            },{
                icon:"icon-pingfen",
            },{
                icon:"icon-wenben",
            },{
                icon:"icon-guanbi",
            },{
                icon:"icon-xiajiantou",
            },{
                icon:"icon-shangjiantou",
            },{
                icon:"icon-icon_loading",
            },{
                icon:"icon-icon_tianjia",
            },{
                icon:"icon-icon_yulan",
            },{
                icon:"icon-icon_zhanghao",
            },{
                icon:"icon-icon_wangye",
            },{
                icon:"icon-icon_shezhi",
            },{
                icon:"icon-icon_baocun",
            },{
                icon:"icon-icon_yingyongguanli",
            },{
                icon:"icon-gongyezujian-kaiguan",
            },{
                icon:"icon-tubiao-zhuzhuangtu",
            },{
                icon:"icon-dui",
            },{
                icon:"icon-riqi",
            },{
                icon:"icon-loding",
            },{
                icon:"icon-kongxinduigou",
            },{
                icon:"icon--zhongdaweixian",
            },{
                icon:"icon-tab",
            },{
                icon:"icon-yunduanxiazai",
            },{
                icon:"icon-yunduanshangchuan",
            },{
                icon:"icon-xian",
            },{
                icon:"icon-kefu",
            },{
                icon:"icon-dankuang-changjingtupian",
            },{
                icon:"icon-table",
            },{
                icon:"icon-xuanzhong1",
            },{
                icon:"icon-xuanzhong2",
            },{
                icon:"icon-dingwei",
            },{
                icon:"icon-shangchuan1",
            },{
                icon:"icon-xiaoxitongzhi",
            },{
                icon:"icon-guangbo",
            },{
                icon:"icon-wifi",
            },{
                icon:"icon-cuowu",
            },{
                icon:"icon-dianhua",
            },{
                icon:"icon-fenxiang1",
            },{
                icon:"icon-gouwuche",
            },{
                icon:"icon-guanliyuan",
            },{
                icon:"icon-qunliao",
            },{
                icon:"icon-qunliao1",
            },{
                icon:"icon-yincang",
            },{
                icon:"icon-fangda",
            },{
                icon:"icon-dingdan",
            },{
                icon:"icon-hehuoren",
            },{
                icon:"icon-fuxuankuang_xuanzhong",
            },{
                icon:"icon-fuxuankuang_xuanzhong1",
            },{
                icon:"icon-fuxuankuang_weixuanzhong",
            },{
                icon:"icon-fuxuankuang_xuanzhong2",
            },{
                icon:"icon-fuxuankuang_xuanzhong3",
            },{
                icon:"icon-fuxuankuang_weixuanzhong1",
            },{
                icon:"icon-fuxuankuang_xuanzhong4",
            },{
                icon:"icon-fuxuankuang_xuanzhong5",
            },{
                icon:"icon-shanchu",
            },{
                icon:"icon-xinzeng",
            },{
                icon:"icon-ditu-dibiao",
            },{
                icon:"icon-ditu-huan",
            },{
                icon:"icon-ditu-xing",
            },{
                icon:"icon-zhuye",
            },{
                icon:"icon-shanchusekuai",
            },{
                icon:"icon-fabusekuai",
            },{
                icon:"icon-tixingshixin",
            },{
                icon:"icon-jian",
            },{
                icon:"icon-jia",
            },{
                icon:"icon-qiapianmoshi_kuai",
            },{
                icon:"icon-upload",
            },{
                icon:"icon-yishixiao",
            },{
                icon:"icon-youxupailie",
            },{
                icon:"icon-xiaolian",
            },{
                icon:"icon-zitiyulan",
            },{
                icon:"icon-dianzan_kuai",
            },{
                icon:"icon-shenfenxuanze",
            },{
                icon:"icon-shubiaoshou",
            },{
                icon:"icon-anniu",
            },{
                icon:"icon-hehuoren1",
            },{
                icon:"icon-aixin_shixin",
            },{
                icon:"icon-aixin",
            },{
                icon:"icon-shexiangtou_shiti",
            },{
                icon:"icon-shexiangtou",
            },{
                icon:"icon-shengyin_shiti",
            },{
                icon:"icon-shengyinkai",
            },{
                icon:"icon-tubiao",
            },{
                icon:"icon-gengduo",
            },{
                icon:"icon-dianzan",
            },{
                icon:"icon-hudong",
            },{
                icon:"icon-saoyisao",
            },{
                icon:"icon-tianjiahaoyou",
            },{
                icon:"icon-CUI-icon-chevron-rig",
            },{
                icon:"icon-CUI-icon-chevron-bot",
            },{
                icon:"icon-CUI-icon-chevron-lef",
            },{
                icon:"icon-CUI-icon-chevron-top",
            },{
                icon:"icon-CUI-icon-close",
            },{
                icon:"icon-CUI-icon-more",
            },{
                icon:"icon-canyin",
            },{
                icon:"icon-dengluyonghu",
            },{
                icon:"icon-fanhuidingbu",
            },{
                icon:"icon-fangchan",
            },{
                icon:"icon-keliuqushi",
            },{
                icon:"icon-mima",
            },{
                icon:"icon-renshengjieduan",
            },{
                icon:"icon-zinv",
            },{
                icon:"icon-zichanqingkuang",
            }
        ]
    }
  },
  methods:{
    licon:function(){
      this.$router.push({
        name:'/home/index',
      });
    }
  },
  mounted(){
    
  },
}
</script>


